# To trigger a Travis-CI build for every GitHub push or Pull Request:
# 1. Goto https://travis-ci.org/profile/rational-insights
# 2. Flip the switch for the `https://github.com/aldanchenko/knime-rational-insights-plugin.git` repo
language: java
matrix:
 fast_finish: true
 include:
 - os: linux
   jdk: openjdk8
   script: xvfb-run mvn verify -B
   before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
      bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
      fi   
 - os: osx
   osx_image: xcode8.3
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
   before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
      bash Miniconda3-latest-MacOSX-x86_64.sh -f -b -p $HOME/conda;
      fi
    - export JAVA_HOME=$(/usr/libexec/java_home)
install:
 - source $HOME/conda/bin/activate root
 - conda install -y -q pandas protobuf
 - pip install pandas
 - mvn package -B
script: xvfb-run mvn verify -B
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
   - $HOME/.cache/pip
   - $HOME/conda
## Uncomment below to perform SonarCloud (https://sonarcloud.io/) analysis,
## Next steps to have automated SonarCloud analysis reports for the repository:
## 1. Create organization at https://sonarcloud.io/account/organizations with 'rational-insights' as name and 'rational-insights' as key
## 2. Add SONAR_TOKEN env var to Travis-CI settings, a token can be generated at https://sonarcloud.io/account/security/
## 3. Push a change to GitHub to trigger a Travis-CI build and SonarCloud analysis
#after_success:
#- mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
